        
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #       dialect: org.hibernate.dialect.MySQL57Dialect
  # datasource:
  #   url: jdbc:mysql://localhost:3306/petstore
  #   username: root
  #   password: admin
  #   driverClassName: com.mysql.cj.jdbc.Driver
  
  # h2:
  #   console:
  #     enabled: true
  # datasource:
  #   driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
  #   url: jdbc:mem:testdb  # H2 접속 정보
  #   username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
  #   password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
